USERNAME = "kotsn"
DOWNLOADS_PATH = fr"C:\Users\{USERNAME}\Downloads"
IMAGES_PATH = fr"C:\Users\{USERNAME}\Downloads\IMAGES"
TEXTS_PATH = fr"C:\Users\{USERNAME}\Downloads\TEXTS"
TEXT_EXTENTIONS = {".txt", ".docx", ".xlsx"}
IMAGES_EXTENTIONS = {".png", ".jpg", ".gif", ".tiff", ".avif"}
APP_EXTENTIONS = {".exe", ".msi"}
APPS_PATH = fr"C:\Users\{USERNAME}\Downloads\APPS\\"
ARCHIVE_EXTANTIOS = {".rar", ".7z", ".zip", ".tgz"}
ARCHIVE_PATH = fr"C:\Users\{USERNAME}\Downloads\ARCHIVES"
MUSIC_EXTENTIONS = {".mp3", ".ogg"}
PDF_EXTENTIONS = ".pdf"
PDF_PATH = fr"C:\Users\{USERNAME}\Downloads\PDF_FILES"
MUSIC_PATH = fr"C:\Users\{USERNAME}\Downloads\MUSIC"
JAR_EXTENTIONS = ".jar"
JAR_PATH = fr"C:\Users\{USERNAME}\Downloads\JAR_FILES"
VIDEOS_EXTENTIONS = {".mp4", ".mov", ".avi", ".mkv"}
VIDEOS_PATH = fr"C:\Users\{USERNAME}\Downloads\VIDEOS"
EXTENTIONS_LIST = (TEXT_EXTENTIONS, IMAGES_EXTENTIONS, APP_EXTENTIONS, ARCHIVE_EXTANTIOS, MUSIC_EXTENTIONS, PDF_EXTENSIONS, JAR_EXTENTIONS, VIDEOS_EXTENTIONS)  