DOWNLOADS_PATH = r"C:\Users\kotsn\Downloads"
IMAGES_PATH = r"C:\Users\kotsn\Downloads\IMAGES"
TEXTS_PATH = r"C:\Users\kotsn\Downloads\TEXTS"
TEXT_EXTENTIONS = {".txt", ".docx", ".xlsx"}
IMAGES_EXTANTIONS = {".png", ".jpg", ".gif", ".tiff", ".avif"}
APP_EXTANTIONS = {".exe", ".msi"}
APPS_PATH = r"C:\Users\kotsn\Downloads\APPS\\"
ARCHIVE_EXTANTIOS = {".rar", ".7z", ".zip", ".tgz"}
ARCHIVE_PATH = r"C:\Users\kotsn\Downloads\ARCHIVES"
MUSIC_EXTANTIONS = {".mp3", ".ogg"}
PDF_EXTENSIONS = ".pdf"
PDF_PATH = r"C:\Users\kotsn\Downloads\PDF_FILES"
MUSIC_PATH = r"C:\Users\kotsn\Downloads\MUSIC"
JAR_EXTENTIONS = ".jar"
JAR_PATH = r"C:\Users\kotsn\Downloads\JAR_FILES"
VIDEOS_EXTENTIONS = {".mp4", ".mov", ".avi", ".mkv"}
VIDEOS_PATH = r"C:\Users\kotsn\Downloads\VIDEOS"
EXTENTIONS_LIST = (TEXT_EXTENTIONS, IMAGES_EXTANTIONS, APP_EXTANTIONS, ARCHIVE_EXTANTIOS, MUSIC_EXTANTIONS, PDF_EXTENSIONS, MUSIC_EXTANTIONS, JAR_EXTENTIONS, VIDEOS_EXTENTIONS)  