USERNAME = "morecat"
DOWNLOADS_PATH = fr"/home/{USERNAME}/Downloads/"
IMAGES_PATH = fr"/home/{USERNAME}/Downloads/IMAGES"
TEXTS_PATH = fr"/home/{USERNAME}/Downloads/TEXTS"
TEXT_EXTENSIONS = {".txt", ".docx", ".xlsx"}
IMAGES_EXTENSIONS = {".png", ".jpg", ".gif", ".tiff", ".avif"}
APP_EXTENSIONS = {".exe", ".msi"}
APPS_PATH = fr"/home/{USERNAME}/Downloads/APPS\\"
ARCHIVE_EXTENSIONS = {".rar", ".7z", ".zip", ".tgz"}
ARCHIVE_PATH = fr"/home/{USERNAME}/Downloads/ARCHIVES"
MUSIC_EXTENSIONS = {".mp3", ".ogg"}
PDF_EXTENSIONS = ".pdf"
PDF_PATH = fr"/home/{USERNAME}/Downloads/PDF_FILES"
MUSIC_PATH = fr"/home/{USERNAME}/Downloads/MUSIC"
JAR_EXTENSIONS = ".jar"
JAR_PATH = fr"/home/{USERNAME}/Downloads/JAR_FILES"
VIDEOS_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv"}
VIDEOS_PATH = fr"/home/{USERNAME}/Downloads/VIDEOS"
EXTENSIONS_LIST = (TEXT_EXTENSIONS, IMAGES_EXTENSIONS, APP_EXTENSIONS, ARCHIVE_EXTENSIONS, MUSIC_EXTENSIONS, PDF_EXTENSIONS, JAR_EXTENSIONS, VIDEOS_EXTENSIONS)  